name: Post release
on:
  release:
    types: [published, released]

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Create changelog
        uses: rhysd/changelog-from-release/action@v3
        with:
          file: CHANGELOG.md
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: CHANGELOG.md
